"""Worxforu service records (Consultio `service` post type). Copy source: docs/worxforu/02-content.md."""

DELIVER = ('<p><strong>1. Discover:</strong> understand goals, users, current systems and constraints.</p>'
           '<p><strong>2. Scope:</strong> agree deliverables, integrations, timeline and responsibilities in writing.</p>'
           '<p><strong>3. Build and test:</strong> deliver in reviewable stages, tested against agreed examples.</p>'
           '<p><strong>4. Launch and support:</strong> train users, hand over documentation and support to the agreed plan.</p>')
FAQ = ('<p><strong>Can you work with our existing software?</strong><br/>We assess your systems, available APIs and access permissions before confirming integration scope.</p>'
       '<p><strong>Can we start with a small project?</strong><br/>Yes. A defined pilot or first module validates requirements and approach before a wider rollout.</p>'
       '<p><strong>How long will implementation take?</strong><br/>It depends on scope, integrations, data quality and review cycles. You receive a delivery plan after discovery.</p>'
       '<p><strong>Do you provide support after launch?</strong><br/>Support can be included in the agreed scope, with coverage and response expectations documented in the proposal.</p>')
PRICING = ('<p>Pricing depends on modules, users, customisation, integrations and deployment requirements. '
           'Share your requirements for a scoped proposal.</p>')

# (post_id or None to create, slug, category, icon, title, excerpt, heading, intro, scope, included[], extra_faq_html)
SERVICES = [
 (446, 'ai-solutions', 'corporate', 'flaticon-idea', 'AI Solutions',
  'AI that supports everyday business work: assistants, document AI and knowledge search.',
  'AI Solutions for Business',
  'Turn approved business information into useful assistance for your team and customers. Worxforu scopes AI assistants, document workflows and knowledge search around a specific operational need.',
  'Each project covers a defined use case, approved data sources, evaluation examples, access rules, a human handoff route and monitoring. AI outputs can contain errors, so we design for review and correction rather than unrestricted autonomous action.',
  ['Internal knowledge assistant', 'Customer enquiry support', 'Document extraction', 'Lead qualification', 'Internal search', 'Assisted drafting and reporting'],
  '<p><strong>Will AI responses always be correct?</strong><br/>No. AI outputs can contain errors. Solutions use approved sources, evaluation and human review appropriate to the task.</p>'),
 (448, 'erp-crm', 'corporate', 'flaticon-network', 'ERP and CRM Software',
  'Connect customer activity with business operations: CRM, ERP, migration and integration.',
  'ERP and CRM Software for Connected Operations',
  'Organise customer relationships and operational information in systems aligned with your business. Start with the modules you need, then plan integrations, migration and reporting.',
  'We define users, modules, data migration, roles, approval flows, integrations and training. CRM consulting covers system selection, setup, sales stages, automation and user training. Accounting, payroll and tax functions need separately confirmed scope and validation.',
  ['Lead, deal and pipeline management', 'Quotations and follow-ups', 'Inventory, purchasing and suppliers', 'Order and approval workflows', 'Role-based access', 'Operational dashboards'], ''),
 (649, 'business-automation', 'corporate', 'flaticon-settings', 'Business Automation',
  'Reduce repetitive work across your business tools with logged, human-controlled workflows.',
  'Business Automation That Connects Your Work',
  'Move information between your tools and reduce repetitive steps in everyday processes. Define the workflow, keep people in control of approvals and make exceptions visible. Example: website enquiry, validate and deduplicate, create lead, assign owner, notify team, schedule follow-up, log the result.',
  'Each workflow maps triggers, conditions, actions, approvals, retries and exception owners, with logs and duplicate protection. Third-party API permissions and usage costs are confirmed before build.',
  ['Enquiry routing', 'Reminders and follow-ups', 'Document approvals', 'Employee and customer onboarding', 'Ticket escalation', 'Scheduled reports and data sync'], ''),
 (2627, 'custom-software', 'corporate', 'flaticon-code', 'Custom Software Development',
  'Software shaped around your business process: internal systems, portals and SaaS apps.',
  'Software Shaped Around Your Business Process',
  'When off-the-shelf tools force workarounds, custom software can fit the way your team actually works. We plan, build and hand over applications to an agreed scope, including full-stack and backend development.',
  'Discovery, requirements, prototypes, implementation, testing, deployment and handover. Source-code ownership and ongoing support are defined in the quotation.',
  ['Internal business systems', 'Customer and vendor portals', 'SaaS applications', 'Booking and inventory tools', 'Admin panels and dashboards', 'Authentication and access control'], ''),
 (645, 'web-mobile-development', 'corporate', 'flaticon-smartphone', 'Website and Mobile Development',
  'Business websites, ecommerce and Android/iOS apps connected to your operations.',
  'Digital Experiences Connected to Your Operations',
  'Websites and apps work harder when they connect to the systems behind them. Worxforu designs and builds business websites, ecommerce stores and mobile applications linked to your CRM, inventory and workflows.',
  'We specify platforms, user journeys, content ownership, accessibility, integrations and maintenance for each project. Platform and integration choices are confirmed after assessment.',
  ['Business websites and CMS', 'Ecommerce development', 'Android and iOS applications', 'Web applications', 'Forms and CRM integration', 'Analytics and conversion tracking'], ''),
 (647, 'technology-consulting', 'corporate', 'flaticon-consultation', 'Technology Consulting and Support',
  'Plan the right system and keep it working: roadmaps, modernisation, cloud and support.',
  'Plan the Right System and Keep It Working',
  'Good technology decisions start with a clear view of how your business runs. We help you choose, plan and maintain the systems that fit, and deliver a prioritised roadmap with dependencies and estimates.',
  'Support hours are Monday to Saturday, 10am to 7pm (Sunday closed). Response targets, backups and monitoring follow an agreed service plan. Compliance workflow implementation follows requirements defined by you and your qualified advisers; we do not provide legal advice.',
  ['Process review', 'Software selection', 'Architecture planning', 'Legacy modernisation', 'Integration planning', 'Compliance workflow implementation'], ''),
 (651, 'seo-optimization', 'business', 'flaticon-search', 'SEO Services',
  'Get found by customers searching for what you offer, in search and AI answers.',
  'SEO Services',
  'A good website needs to be found. We improve how search engines and AI assistants understand your site, so the right customers reach you.',
  'Rankings depend on competition, content and search-engine changes. We commit to agreed work and transparent reporting, not guaranteed positions.',
  ['Technical SEO audit and fixes', 'Keyword and search-intent research', 'On-page optimisation', 'Local SEO and Google Business Profile', 'Content strategy and structured data', 'Search Console and analytics reporting'],
  '<p><strong>How long does SEO take?</strong><br/>Technical fixes can show effects within weeks; content and authority usually build over several months. We agree milestones up front.</p>'),
 (2625, 'market-research-and-advertising', 'business', 'flaticon-chart', 'Market Research',
  'Understand your market, customers and competitors before you invest.',
  'Market Research for Better Decisions',
  'Before you build, launch or expand, know who your customers are, what they want and who you are up against.',
  'Research methods, sample sizes and data sources are agreed before fieldwork. Findings are reported with their limitations.',
  ['Market and opportunity sizing', 'Competitor analysis', 'Customer surveys and interviews', 'Search-demand and trend analysis', 'Pricing and positioning research', 'Findings report with recommendations'], ''),
 (4171, 'web-portals', 'business', 'flaticon-browser', 'Web Portals',
  'Secure portals for customers, vendors, employees and partners.',
  'Web Portals for Customers, Vendors and Teams',
  'Give each group a secure place to find information, submit requests and complete tasks without email back-and-forth.',
  'Authentication, permissions, audit logs and data ownership are scoped for every project.',
  ['Customer portals', 'Vendor and supplier portals', 'Employee self-service', 'Partner portals', 'Forms and document workflows', 'Business-system integration'], ''),
 (4174, 'learning-management-systems', 'business', 'flaticon-graduation', 'Learning Management Systems',
  'Deliver courses, assessments and progress tracking in one place.',
  'Learning Management Systems',
  'Organise training and courses in one place, with clear progress tracking for learners and administrators.',
  'Video hosting, content migration, certification and integrations are confirmed separately for each project.',
  ['Course organisation', 'User enrolment', 'Assessments', 'Progress reporting', 'Role-based administration', 'Integrations'], ''),
 (4177, 'saas-implementation', 'business', 'flaticon-cloud', 'SaaS Consultation and Implementation',
  'Select, configure and adopt the right subscription software.',
  'SaaS Consultation and Implementation',
  'Subscription software only pays off when it is set up well and actually used. We help you choose, configure and adopt it.',
  'Third-party subscription licences are billed by the vendor and are separate from Worxforu implementation fees.',
  ['Software selection', 'Configuration', 'User onboarding', 'Integration with existing systems', 'Adoption support', 'Admin training'], ''),
 (None, 'ui-ux-design', 'business', 'flaticon-design', 'UI and UX Design',
  'Clear user journeys for applications and business systems.',
  'UI and UX Design for Business Systems',
  'Complex systems should still be easy to use. We plan user journeys before development so the software your team adopts is the software you built.',
  'This is a service for your applications and systems, delivered through discovery, flows, wireframes and prototypes.',
  ['Discovery', 'User flows', 'Wireframes', 'Prototypes', 'Usability review', 'Design handover'], ''),
 (None, 'cloud-solutions', 'business', 'flaticon-cloud', 'Cloud Migration and Hosting',
  'Move and run business applications on well-managed cloud environments.',
  'Cloud Migration and Hosting',
  'Move business applications to well-managed cloud environments with a clear plan for backups, monitoring and cost.',
  'Hosting fees are separate from implementation and support fees.',
  ['Migration planning', 'Environment setup', 'Backups', 'Monitoring', 'Security baseline', 'Cost review'], ''),
 (None, 'devops', 'business', 'flaticon-settings', 'DevOps and Deployment Automation',
  'Repeatable builds, tested releases and safe rollbacks.',
  'DevOps and Deployment Automation',
  'Release changes with confidence using repeatable builds, automated tests and a tested way back.',
  'Pipelines, environments and rollback procedures are documented and handed over.',
  ['Build pipelines', 'Automated testing', 'Release processes', 'Environment configuration', 'Rollback procedures', 'Documentation'], ''),
 (None, 'api-integration', 'business', 'flaticon-network', 'API Development and Integration',
  'Connect your systems through reliable, monitored data flows.',
  'API Development and Integration',
  'Connect the systems you rely on so data moves reliably, without manual exports and imports.',
  'Rate limits, retries, failure handling and data ownership are defined for every integration.',
  ['API design and documentation', 'Authenticated endpoints', 'System-to-system integration', 'Monitoring and alerts', 'Error handling and retries', 'Data mapping'], ''),
 (None, 'data-analytics', 'business', 'flaticon-chart', 'Data Management and Analytics',
  'Clean data and dashboards built around real business measures.',
  'Data Management and Analytics',
  'Organise operational data and turn it into dashboards your team can act on.',
  'Source systems, data-quality checks and report access are specified for each project.',
  ['Data organisation', 'Record migration', 'Data-quality checks', 'KPI definition', 'Dashboards and reports', 'Access control'], ''),
 (None, 'support-maintenance', 'business', 'flaticon-support', 'Maintenance, Training and Support',
  'Keep systems current, documented and well understood.',
  'Maintenance, Training and Support',
  'Keep systems current, secure and well understood after launch.',
  'Support hours: Monday to Saturday, 10am to 7pm (Sunday closed). Response targets and any out-of-hours cover are set out in your service plan.',
  ['Scheduled updates', 'Incident handling', 'Documentation', 'User training', 'Performance checks', 'Backup verification'], ''),
 (None, 'ecommerce-development', 'business', 'flaticon-shopping-cart', 'Ecommerce Development',
  'Online stores connected to your inventory and orders.',
  'Ecommerce Built Around Your Operations',
  'Sell online without running a second business in spreadsheets. We connect your catalogue, orders and stock in one flow.',
  'Payment gateway fees and platform subscriptions are billed by the provider.',
  ['Product and catalogue management', 'Checkout through approved payment providers', 'Shipping integration', 'Inventory integration', 'Order notifications', 'Customer accounts'], ''),
 (None, 'mobile-app-development', 'business', 'flaticon-smartphone', 'Android and iOS Applications',
  'Mobile apps for customers and internal teams.',
  'Android and iOS Applications',
  "Put your service in your customers' pockets, or give field teams the tools they need on the move.",
  'Platform choice (native or cross-platform) is confirmed after assessing your users, features and budget.',
  ['Platform selection', 'Interface design', 'Backend and API connectivity', 'Device testing', 'App Store and Play Store release', 'Post-launch updates'], ''),
]
